import { useEffect, useState } from 'react'
import { Trash2 } from 'lucide-react'
import { format } from 'date-fns'
import Modal from '@/components/Modal'
import { supabase } from '@/lib/supabase'
import type { Reminder } from '@/types'

export default function ReminderModal({open,onClose,onSaved,reminder}:{open:boolean;onClose:()=>void;onSaved:()=>void;reminder?:Reminder|null}){
  const [title,setTitle]=useState('');const [note,setNote]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('');const [priority,setPriority]=useState<'low'|'medium'|'high'>('medium');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{setTitle(reminder?.title??'');setNote(reminder?.note??'');if(reminder?.due_at){const d=new Date(reminder.due_at);setDate(format(d,'yyyy-MM-dd'));setTime(format(d,'HH:mm'))}else{setDate('');setTime('')}setPriority(reminder?.priority??'medium');setError('')},[reminder,open])
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const due=date?new Date(`${date}T${time||'23:59'}:00`).toISOString():null;const payload={title:title.trim(),note:note.trim()||null,due_at:due,priority};const {error:err}=reminder?await supabase.from('reminders').update(payload).eq('id',reminder.id):await supabase.from('reminders').insert(payload);if(err)setError(err.message);else{onSaved();onClose()}setBusy(false)}
  async function remove(){if(!reminder||!confirm('Excluir este lembrete?'))return;setBusy(true);const {error:err}=await supabase.from('reminders').delete().eq('id',reminder.id);if(err)setError(err.message);else{onSaved();onClose()}setBusy(false)}
  return <Modal open={open} onClose={onClose} title={reminder?'Editar lembrete':'Novo lembrete'}><form className="grid gap-4" onSubmit={save}><div className="field"><label>Título</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Ex.: Entregar atividade"/></div><div className="grid grid-cols-2 gap-3"><div className="field"><label>Data limite</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Horário</label><input className="input" type="time" value={time} onChange={e=>setTime(e.target.value)} disabled={!date}/></div></div><div className="field"><label>Prioridade</label><select className="select" value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></div><div className="field"><label>Notas</label><textarea className="textarea" value={note} onChange={e=>setNote(e.target.value)}/></div>{error&&<p className="rounded-xl bg-[#fff2f2] px-3 py-2 text-sm text-danger">{error}</p>}<div className="flex items-center justify-between">{reminder?<button className="secondary-button text-danger" type="button" onClick={()=>void remove()} disabled={busy}><Trash2 size={16}/>Excluir</button>:<span/>}<button className="primary-button" disabled={busy}>{busy?'Salvando…':'Salvar lembrete'}</button></div></form></Modal>
}
